{% set name = "puncc" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/puncc-{{ version }}.tar.gz
  sha256: 15da66451c70e2f91c06a3176c42fe7d9a971957d2f68bb982185f2badd0eece

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - scikit-learn
    - tqdm

test:
  imports:
    - deel.puncc
    - deel.puncc.api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deel-ai/puncc
  summary: Predictive UNcertainty Calibration and Conformalization Library
  license_file: MIT-Clause.txt
  license: MIT

extra:
  recipe-maintainers:
    - M-Mouhcine
    - CyrilJl
